
title: <p align="center"> Aishah Jhumka </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  
  <br>   
  I am currently working on Data Science and Machine learning related problems.
  <br>
  </p>


theme: jekyll-theme-minimal
